"""create diagnosis table

Revision ID: 8d3bb6d540d8
Revises: 9c0d90f7aec8
Create Date: 2026-07-07 12:35:32.646774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3bb6d540d8'
down_revision: Union[str, Sequence[str], None] = '9c0d90f7aec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
